name: 11.5 Linting workflow!

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: heroku deployment
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokemonnikortit
          heroku_email: asturune@hotmail.com
          healthcheck: https://pokemonnikortit.herokuapp.com/health #ks. endpoint app.js filestä muutoksia
          rollbackonhealthcheckfailed: true #tekee rollbackin, jos deployment feilaa Herokuunss
      - uses: actions/checkout@v2 #Checkout uudelleen, ettei tule virhettä workflowin ajossa-->ei pysty muuten lisäämään tag:a
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }} #tällä varmistetaan, että vain main branch muutokset luovat uuden version
        uses: anothrNick/github-tag-action@1.36.0 #Open source versioning action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch" #defaulttina minor ja tässä halutaan muuttaa defaultiksi patch